# ===========================================
# Site Information Settings
# ===========================================

# Site creation time
since: 2015

# Custom your favicon.ico in `site/source`
favicon: /favicon.ico

# Set feed link (false | default | your feed link)
# false: disable
# default: use `atom.xml`, generator for `hexo-generator-feed`
rss: default

# ===========================================
# Menu Settings
# ===========================================
menu:
  Home: /
  Archives: /archives/
  Tags: /tags
  Categories: /categories
  About: /about

# ===========================================
# Theme Settings
# ===========================================
# theme styling
# color: Default | Mint Green | Cobalt Blue | Hot Pink | Dark Violet
theme:
  color: Default
  toc: false
  fancybox: false

copyright:
  enable: false
  # https://creativecommons.org/
  license: '本文采用<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/" target="_blank">知识共享署名-非商业性使用 4.0 国际许可协议</a>进行许可'

reward:
  enable: false
  qrCode:
    wechat: /image/reward/wechat.png
    alipay: /image/reward/alipay.png

# ===========================================
# Social links Settings
# ===========================================
social:
  email: beijiu572@gmail.com
  stack-overflow: https://stackoverflow.com/users/1841463/kevin-guo
  twitter: https://twitter.com/cielpy5
  facebook:
  linkedin:
  google:
  github: https://github.com/cielpy
  weibo:
  zhihu:
  pocket:
  tumblr:

# ===========================================
# Third Party Services Settings
# ===========================================

# Baidu Analytics
baidu_analytics: 0a275bcf7d954b807e1db498d8e5b192
# Baidu Verification
baidu_verification: 0a275bcf7d954b807e1db498d8e5b192

# Google Analytics
google_analytics: UA-51259806-3

# Google Verification
google_verification: j5dWC85DkoAfUR50W00ewfii3X9ouH55HnyBP6oZxGE

disqus_shortname: cielpark
# ===========================================
# Version
# ===========================================
version: 2.4.x
